#Classes and Functions

In [0]:
class Person:
  department = 'School Of information'
  def set_name(self,new_name):
    self.name = new_name

In [235]:
x= Person()
x.set_name('Darshan')
print('{} lives in india'.format(x.name))

Darshan lives in india


#map()

In [0]:
store1 = [10.1,0.23,12.56,14.2]
store2 = [5.5,2.2,1.,14.3]

In [78]:
print(map(min,store1,store2))
list(map(min,store1,store2))

[5.5, 0.23, 1.0, 14.2]

In [18]:
names = ['Dr.Darshan Suthar','Dr.shubhas rao','Dr.Ram Chandra']

def split_titless_lastname(lsname):
  titles = lsname.split('.')[0]
  lastname = lsname.split()[-1]
  return '{}. {}'.format(titles,lastname)

list(map(split_titless_lastname,names))

['Dr. Suthar', 'Dr. rao', 'Dr. Chandra']

#How to use lambda 

In [28]:
x = lambda a,b,c : (a+b)*c
print(x(1,2,3))

9


#Create list of even number between 0 and 1000

In [0]:
even = []

for number in range(0,1000):
  if number % 2 == 0:
    even.append(number)

# print(even)

#Easy way to do it

In [0]:
even = [number for number in range(0,1000) if number %2==0]
# even

#Problem

Many organizations have user ids which are constrained in some way. Imagine you work at an internet service provider and the user ids are all two letters followed by two numbers (e.g. aa49). Your task at such an organization might be to hold a record on the billing activity for each possible user.

Write an initialization line as a single list comprehension which creates a list of all possible user ids. Assume the letters are all lower case.

In [0]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

ans = []

for a in lowercase:
  for b in lowercase:
    for c in digits:
      for d in digits:
        ans.append(a+b+c+d)
        

#Easy way to do it

In [32]:
answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

ans == answer

True

<h1> Numpy</h1>

In [0]:
import numpy as np

#Numpy arrays

In [37]:
#1d array
one_d = np.array([1,2,3])
one_d.shape

(3,)

In [35]:
#2d array or matrix
two_d = np.array([[1,2,3],
                  [4,5,6]])
two_d.shape

(2, 3)

In [39]:
#3d array 
three_d = np.array([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]],
                    [[13,14,15],[16,17,18]]])
three_d.shape

(3, 2, 3)

#(1) Arange

In [42]:
even = np.arange(0,30,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [44]:
odd = np.arange(1,30,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

#(2) Reshape

In [49]:
re_even = even.reshape(3,5)
re_even

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

#(3) Linspace

In [51]:
spc = np.linspace(0,5,10)
spc

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

#(4) ones, zeros and eye

In [57]:
#np.ones
ones = np.ones([4,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
#np.zeros
zeros = np.zeros([4,4])
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
#np.eye
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Repeat

In [67]:
#repeating without using np.repeat
arr = np.array([1,2,3]*3,int)
print(arr)

#np.repeat
a = np.array([1,2,3],int)
np.repeat(a,3)

[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#vstack and hstack

In [82]:
print(np.vstack([a,a*2]))
print(np.hstack([a,a*2]))

[[1 2 3]
 [2 4 6]]
[1 2 3 2 4 6]


<h1>Array operation</h1>

In [0]:
aa = np.array([[1,2,3],[4,5,6]])

In [93]:
#addition
aa+aa

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [95]:
#subtraction
aa-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [96]:
#multiplication
aa*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [97]:
#division
aa/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [100]:
#dot product
np.dot(aa,a)

array([14, 32])

In [101]:
#transpose
aa.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [103]:
#power
aa**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [107]:
#casting array to different type
aaa = aa.astype('float64')
aaa

array([[1., 2., 3.],
       [4., 5., 6.]])

In [108]:
#sum of all values
aa.sum()

21

In [109]:
#maximum value
aa.max()

6

In [110]:
#minimun value
aa.min()

1

In [111]:
#mean
aa.mean()

3.5

In [112]:
#standard deviation
aa.std()

1.707825127659933

In [113]:
#for index of min value
aa.argmin()

0

In [114]:
#for index of max value
aa.argmax()

5

#Slicing

In [116]:
b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [123]:
#first element
b[0]

0

In [132]:
#last element
print(b[len(b)-1])
#easy way
print(b[-1])

19
19


In [134]:
#second last element
b[-2]

18

In [126]:
#first five element
b[0:5]

array([0, 1, 2, 3, 4])

In [128]:
#elements from index 5 to 10(10th element not included)
b[5:10]

array([5, 6, 7, 8, 9])

In [129]:
#element from index 5 to end of array
b[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [130]:
#element from start of array to index 16
b[:16]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [143]:
#from last to first
b[-4:]

array([16, 17, 18, 19])

In [146]:
b[-4::-2]

array([16, 14, 12, 10,  8,  6,  4,  2,  0])

#Slicing for 2D array

In [167]:
s = np.arange(25)
s= s.reshape((5,5))
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [166]:
s[0,4]

4

In [171]:
s[0:,4]


array([ 4,  9, 14, 19, 24])

In [178]:
#every second element of last row
print(s[-1, ::2])

#every second element of first row
print(s[0,::2])

[20 22 24]
[0 2 4]


In [183]:
#elements greater than 6 replacing it with 20
s[s>6] = 20 
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [185]:
s2 = s[:3,:3]
s2[:]=0
s2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [187]:
#by changing the values of s2, original array s will also be changed
print(s)

[[ 0  0  0  3  4]
 [ 0  0  0 20 20]
 [ 0  0  0 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]]


In [193]:
#to copy an array 
s3 = s.copy()
s3[:3,:3]= 2
s3

array([[ 2,  2,  2,  3,  4],
       [ 2,  2,  2, 20, 20],
       [ 2,  2,  2, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [201]:
#by changing the values of s3, original array will remain same
s

array([[ 0,  0,  0,  3,  4],
       [ 0,  0,  0, 20, 20],
       [ 0,  0,  0, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

#Iterating over Arrays

In [208]:
#creating arrays with random elements
itr = np.random.randint(0,10,(5,4))
itr

array([[6, 9, 1, 2],
       [6, 6, 7, 9],
       [8, 8, 1, 3],
       [3, 6, 2, 4],
       [8, 2, 1, 5]])

In [220]:
for row in itr:
  print(row)

[6 9 1 2]
[6 6 7 9]
[8 8 1 3]
[3 6 2 4]
[8 2 1 5]


In [218]:
for i in range(len(itr)):
  print(itr[i])



[6 9 1 2]
[6 6 7 9]
[8 8 1 3]
[3 6 2 4]
[8 2 1 5]


In [225]:
list(enumerate(itr))

[(0, array([6, 9, 1, 2])),
 (1, array([6, 6, 7, 9])),
 (2, array([8, 8, 1, 3])),
 (3, array([3, 6, 2, 4])),
 (4, array([8, 2, 1, 5]))]

In [227]:
for i,row in enumerate(itr):
  print('row',i,'is',row)

row 0 is [6 9 1 2]
row 1 is [6 6 7 9]
row 2 is [8 8 1 3]
row 3 is [3 6 2 4]
row 4 is [8 2 1 5]


In [232]:
itr2 = itr*2
itr2

array([[12, 18,  2,  4],
       [12, 12, 14, 18],
       [16, 16,  2,  6],
       [ 6, 12,  4,  8],
       [16,  4,  2, 10]])

In [233]:
for i,j in zip(itr,itr2):
  print(i,' * ',j,' = ',i*j)

[6 9 1 2]  *  [12 18  2  4]  =  [ 72 162   2   8]
[6 6 7 9]  *  [12 12 14 18]  =  [ 72  72  98 162]
[8 8 1 3]  *  [16 16  2  6]  =  [128 128   2  18]
[3 6 2 4]  *  [ 6 12  4  8]  =  [18 72  8 32]
[8 2 1 5]  *  [16  4  2 10]  =  [128   8   2  50]
